const products = [
  {
    id: 1,
    nama: "Dress Floral Vintage Premium",
    harga: 185000,
    hargaAsli: 450000,
    kategori: "wanita",
    kondisi: "Sangat Baik",
    ukuran: "M",
    deskripsi: "Dress floral vintage dengan bahan premium, kondisi sangat baik. Cocok untuk acara casual maupun semi-formal. Warna masih cerah dan tidak ada cacat.",
    gambar: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop",
    rating: 4.8,
    terjual: 23
  },
  {
    id: 2,
    nama: "Kemeja Batik Pria Eksklusif",
    harga: 125000,
    hargaAsli: 320000,
    kategori: "pria",
    kondisi: "Baik",
    ukuran: "L",
    deskripsi: "Kemeja batik pria motif kawung modern. Bahan katun berkualitas tinggi, nyaman dipakai seharian. Cocok untuk acara formal dan non-formal.",
    gambar: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&h=400&fit=crop",
    rating: 4.6,
    terjual: 15
  },
  {
    id: 3,
    nama: "Tas Ransel Anak Karakter",
    harga: 75000,
    hargaAsli: 200000,
    kategori: "anak",
    kondisi: "Sangat Baik",
    ukuran: "One Size",
    deskripsi: "Tas ransel anak dengan karakter lucu, ukuran pas untuk anak SD. Bahan waterproof, ritsleting masih berfungsi sempurna.",
    gambar: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop",
    rating: 4.9,
    terjual: 41
  },
  {
    id: 4,
    nama: "Gelang Silver Minimalis",
    harga: 45000,
    hargaAsli: 150000,
    kategori: "aksesoris",
    kondisi: "Baik",
    ukuran: "One Size",
    deskripsi: "Gelang silver 925 dengan desain minimalis elegan. Tidak ada cacat, kilap masih terjaga. Cocok untuk daily wear maupun acara spesial.",
    gambar: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop",
    rating: 4.7,
    terjual: 67
  },
  {
    id: 5,
    nama: "Blazer Wanita Office Look",
    harga: 220000,
    hargaAsli: 550000,
    kategori: "wanita",
    kondisi: "Sangat Baik",
    ukuran: "S",
    deskripsi: "Blazer wanita formal untuk kebutuhan kantor. Warna navy blue, bahan polyester premium tidak mudah kusut. Perfect untuk tampilan profesional.",
    gambar: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=400&fit=crop",
    rating: 4.8,
    terjual: 18
  },
  {
    id: 6,
    nama: "Celana Jogger Pria Sporty",
    harga: 95000,
    hargaAsli: 250000,
    kategori: "pria",
    kondisi: "Baik",
    ukuran: "XL",
    deskripsi: "Celana jogger pria bahan fleece tebal, nyaman untuk olahraga dan santai. Warna abu-abu, elastis masih bagus, tidak ada robekan.",
    gambar: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400&h=400&fit=crop",
    rating: 4.5,
    terjual: 29
  },
  {
    id: 7,
    nama: "Baju Bayi Newborn Set",
    harga: 55000,
    hargaAsli: 150000,
    kategori: "anak",
    kondisi: "Sangat Baik",
    ukuran: "0-3 Bulan",
    deskripsi: "Set pakaian bayi newborn terdiri dari 3 pcs. Bahan katun organik lembut, tidak mengandung bahan berbahaya. Cocok untuk hadiah baby shower.",
    gambar: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=400&fit=crop",
    rating: 4.9,
    terjual: 52
  },
  {
    id: 8,
    nama: "Kalung Emas Lapis 24K",
    harga: 85000,
    hargaAsli: 280000,
    kategori: "aksesoris",
    kondisi: "Baik",
    ukuran: "45cm",
    deskripsi: "Kalung emas lapis 24K dengan liontin berlian imitasi. Kilau masih sempurna, tidak ada perubahan warna. Tersedia kotak kalung original.",
    gambar: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop",
    rating: 4.6,
    terjual: 34
  },
  {
    id: 9,
    nama: "Rok Midi Plisket Wanita",
    harga: 135000,
    hargaAsli: 350000,
    kategori: "wanita",
    kondisi: "Sangat Baik",
    ukuran: "M",
    deskripsi: "Rok midi plisket bahan satin glossy. Warna dusty pink, tidak mudah kusut dan sangat nyaman dipakai. Cocok untuk berbagai kesempatan.",
    gambar: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400&h=400&fit=crop",
    rating: 4.7,
    terjual: 21
  },
  {
    id: 10,
    nama: "Sepatu Sneakers Pria Nike",
    harga: 350000,
    hargaAsli: 950000,
    kategori: "pria",
    kondisi: "Baik",
    ukuran: "42",
    deskripsi: "Sneakers Nike Air Max kondisi 80%, sole masih tebal. Upper bersih, tidak ada kerusakan signifikan. Cocok untuk daily use.",
    gambar: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    rating: 4.4,
    terjual: 11
  },
  {
    id: 11,
    nama: "Dress Anak Pesta Princess",
    harga: 90000,
    hargaAsli: 240000,
    kategori: "anak",
    kondisi: "Sangat Baik",
    ukuran: "4-5 Tahun",
    deskripsi: "Dress pesta anak tema princess dengan tutu fluffy. Warna pink cerah, payet masih lengkap. Hanya dipakai sekali untuk pesta ulang tahun.",
    gambar: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=400&h=400&fit=crop",
    rating: 4.9,
    terjual: 38
  },
  {
    id: 12,
    nama: "Topi Baseball Vintage",
    harga: 65000,
    hargaAsli: 180000,
    kategori: "aksesoris",
    kondisi: "Baik",
    ukuran: "Adjustable",
    deskripsi: "Topi baseball vintage dengan bordir logo klasik. Bahan twill berkualitas, warna tidak pudar. Cocok untuk gaya kasual dan streetwear.",
    gambar: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&h=400&fit=crop",
    rating: 4.5,
    terjual: 44
  },
  {
    id: 13,
    nama: "Cardigan Rajut Wanita Oversized",
    harga: 165000,
    hargaAsli: 420000,
    kategori: "wanita",
    kondisi: "Sangat Baik",
    ukuran: "L/XL",
    deskripsi: "Cardigan rajut oversized bahan wool blend premium. Warna cream natural, sangat hangat dan stylish. Tidak ada pilling berlebihan.",
    gambar: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=400&fit=crop",
    rating: 4.8,
    terjual: 26
  },
  {
    id: 14,
    nama: "Kemeja Flannel Pria Kotak",
    harga: 110000,
    hargaAsli: 290000,
    kategori: "pria",
    kondisi: "Baik",
    ukuran: "M",
    deskripsi: "Kemeja flannel pria motif kotak-kotak warna merah. Bahan tebal dan hangat, cocok untuk musim hujan. Semua kancing masih lengkap.",
    gambar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    rating: 4.6,
    terjual: 19
  },
  {
    id: 15,
    nama: "Sandal Bayi Lucu Anti Slip",
    harga: 35000,
    hargaAsli: 100000,
    kategori: "anak",
    kondisi: "Sangat Baik",
    ukuran: "6-12 Bulan",
    deskripsi: "Sandal bayi bahan EVA lembut anti slip. Motif kartun lucu, sol tebal dan empuk untuk kenyamanan bayi. Hanya dipakai beberapa kali.",
    gambar: "https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?w=400&h=400&fit=crop",
    rating: 4.8,
    terjual: 73
  },
  {
    id: 16,
    nama: "Cincin Perak Batu Opal",
    harga: 55000,
    hargaAsli: 175000,
    kategori: "aksesoris",
    kondisi: "Sangat Baik",
    ukuran: "17",
    deskripsi: "Cincin perak 925 dengan batu opal asli. Batu masih utuh dan berkilau, tidak ada goresan pada silver. Tersedia kotak cincin velvet.",
    gambar: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop",
    rating: 4.7,
    terjual: 29
  },
  {
    id: 17,
    nama: "Jumpsuit Wanita Casual",
    harga: 195000,
    hargaAsli: 490000,
    kategori: "wanita",
    kondisi: "Sangat Baik",
    ukuran: "S",
    deskripsi: "Jumpsuit wanita one piece bahan linen adem. Warna olive green, model tali adjustable. Sangat nyaman dan trendy untuk berbagai acara casual.",
    gambar: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=400&fit=crop",
    rating: 4.9,
    terjual: 14
  },
  {
    id: 18,
    nama: "Jaket Denim Pria Classic",
    harga: 245000,
    hargaAsli: 620000,
    kategori: "pria",
    kondisi: "Baik",
    ukuran: "L",
    deskripsi: "Jaket denim classic bahan tebal kualitas premium. Warna medium blue, semua kancing dan ritsleting berfungsi normal. Cocok untuk gaya kasual.",
    gambar: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop",
    rating: 4.5,
    terjual: 33
  },
  {
    id: 19,
    nama: "Setelan Anak Sekolah",
    harga: 80000,
    hargaAsli: 210000,
    kategori: "anak",
    kondisi: "Baik",
    ukuran: "6-7 Tahun",
    deskripsi: "Setelan sekolah anak terdiri dari kemeja putih dan celana/rok abu-abu. Kondisi baik, cocok untuk keperluan sekolah.",
    gambar: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&h=400&fit=crop",
    rating: 4.6,
    terjual: 47
  },
  {
    id: 20,
    nama: "Kacamata Sunglasses Retro",
    harga: 75000,
    hargaAsli: 220000,
    kategori: "aksesoris",
    kondisi: "Sangat Baik",
    ukuran: "One Size",
    deskripsi: "Kacamata sunglasses retro dengan frame acetate tebal. Lensa polarized anti UV400, tidak ada goresan. Dengan case kulit original.",
    gambar: "https://images.unsplash.com/photo-1508296695146-257a814070b4?w=400&h=400&fit=crop",
    rating: 4.7,
    terjual: 56
  }
];
